application: fairdiceroll
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /_ah/stats/.*
  script: djangoappengine/appstats/ui.py

- url: /css
  static_dir: assets/css

- url: /js
  static_dir: assets/js

- url: /favicon.ico
  static_files: assets/root/favicon.ico
  upload: assets/root/favicon.ico

- url: /.*
  script: djangoappengine/main/main.py
